# Copyright (C) 2017 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/a5y17lte/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/a5y17lte/proprietary/lib/hw/audio.primary.universal7880.so:system/lib/hw/audio.primary.universal7880.so \
    vendor/samsung/a5y17lte/proprietary/lib/lib_SamsungRec_06002.so:system/lib/lib_SamsungRec_06002.so \
    vendor/samsung/a5y17lte/proprietary/lib/lib_SoundAlive_SRC384_ver300.so:system/lib/lib_SoundAlive_SRC384_ver300.so \
    vendor/samsung/a5y17lte/proprietary/lib/lib_soundaliveresampler.so:system/lib/lib_soundaliveresampler.so \
    vendor/samsung/a5y17lte/proprietary/lib/lib_SoundBooster_ver710.so:system/lib/lib_SoundBooster_ver710.so \
    vendor/samsung/a5y17lte/proprietary/lib/libaudio-ril.so:system/lib/libaudio-ril.so \
    vendor/samsung/a5y17lte/proprietary/lib/libaudioroute.so:system/lib/libaudioroute.so \
    vendor/samsung/a5y17lte/proprietary/lib/libcodecdump.so:system/lib/libcodecdump.so \
    vendor/samsung/a5y17lte/proprietary/lib/librecordalive.so:system/lib/librecordalive.so \
    vendor/samsung/a5y17lte/proprietary/lib/libpreprocessing_nxp.so:system/lib/libpreprocessing_nxp.so \
    vendor/samsung/a5y17lte/proprietary/lib/libSamsungPostProcess.so:system/lib/libSamsungPostProcess.so \
    vendor/samsung/a5y17lte/proprietary/lib/libSamsungPostProcessConvertor.so:system/lib/libSamsungPostProcessConvertor.so \
    vendor/samsung/a5y17lte/proprietary/lib/libsamsungSoundbooster_plus.so:system/lib/libsamsungSoundbooster_plus.so \
    vendor/samsung/a5y17lte/proprietary/lib/libsamsungDiamondVoice.so:system/lib/libsamsungDiamondVoice.so \
    vendor/samsung/a5y17lte/proprietary/lib/libsecaudioinfo.so:system/lib/libsecaudioinfo.so \
    vendor/samsung/a5y17lte/proprietary/lib64/libsecaudioinfo.so:system/lib64/libsecaudioinfo.so \
    vendor/samsung/a5y17lte/proprietary/lib/libsecril-client.so:system/lib/libsecril-client.so \
    vendor/samsung/a5y17lte/proprietary/lib64/libsecril-client.so:system/lib64/libsecril-client.so \
    vendor/samsung/a5y17lte/proprietary/lib/libtinyalsa.so:system/lib/libtinyalsa.so \
    vendor/samsung/a5y17lte/proprietary/lib64/libtinyalsa.so:system/lib64/libtinyalsa.so \
    vendor/samsung/a5y17lte/proprietary/lib/libtinycompress.so:system/lib/libtinycompress.so \
    vendor/samsung/a5y17lte/proprietary/vendor/lib/libLifevibes_lvvetx.so:system/vendor/lib/libLifevibes_lvvetx.so \
    vendor/samsung/a5y17lte/proprietary/vendor/lib/libLifevibes_lvverx.so:system/vendor/lib/libLifevibes_lvverx.so \
    vendor/samsung/a5y17lte/proprietary/lib/libtfa98xx_samsung.so:system/lib/libtfa98xx_samsung.so \
    vendor/samsung/a5y17lte/proprietary/etc/Tfa9896.cnt:system/etc/Tfa9896.cnt \
    vendor/samsung/a5y17lte/proprietary/bin/wcnss_filter:system/bin/wcnss_filter \
    vendor/samsung/a5y17lte/proprietary/lib/libbt-vendor.so:system/lib/libbt-vendor.so \
    vendor/samsung/a5y17lte/proprietary/lib/hw/camera.exynos5.so:system/lib/hw/camera.exynos5.so \
    vendor/samsung/a5y17lte/proprietary/lib64/hw/camera.exynos5.so:system/lib64/hw/camera.exynos5.so \
    vendor/samsung/a5y17lte/proprietary/lib/libexynoscamera.so:system/lib/libexynoscamera.so \
    vendor/samsung/a5y17lte/proprietary/lib64/libexynoscamera.so:system/lib64/libexynoscamera.so \
    vendor/samsung/a5y17lte/proprietary/lib/libexynoscamera3.so:system/lib/libexynoscamera3.so \
    vendor/samsung/a5y17lte/proprietary/lib64/libexynoscamera3.so:system/lib64/libexynoscamera3.so \
    vendor/samsung/a5y17lte/proprietary/lib/libuniapi.so:system/lib/libuniapi.so \
    vendor/samsung/a5y17lte/proprietary/lib64/libuniapi.so:system/lib64/libuniapi.so \
    vendor/samsung/a5y17lte/proprietary/lib/libuniplugin.so:system/lib/libuniplugin.so \
    vendor/samsung/a5y17lte/proprietary/lib64/libuniplugin.so:system/lib64/libuniplugin.so \
    vendor/samsung/a5y17lte/proprietary/lib/libhwjpeg.so:system/lib/libhwjpeg.so \
    vendor/samsung/a5y17lte/proprietary/lib64/libhwjpeg.so:system/lib64/libhwjpeg.so \
    vendor/samsung/a5y17lte/proprietary/vendor/firmware/setfile_3p8_front.bin:system/vendor/firmware/setfile_3p8_front.bin \
    vendor/samsung/a5y17lte/proprietary/vendor/firmware/setfile_3p8.bin:system/vendor/firmware/setfile_3p8.bin \
    vendor/samsung/a5y17lte/proprietary/vendor/lib/mediadrm/libdrmclearkeyplugin.so:system/vendor/lib/mediadrm/libdrmclearkeyplugin.so \
    vendor/samsung/a5y17lte/proprietary/vendor/lib64/mediadrm/libdrmclearkeyplugin.so:system/vendor/lib64/mediadrm/libdrmclearkeyplugin.so \
    vendor/samsung/a5y17lte/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
    vendor/samsung/a5y17lte/proprietary/lib64/libbauthserver.so:system/lib64/libbauthserver.so \
    vendor/samsung/a5y17lte/proprietary/lib64/libbauthtzcommon.so:system/lib64/libbauthtzcommon.so \
    vendor/samsung/a5y17lte/proprietary/lib64/libegis_fp_normal_sensor_test.so:system/lib64/libegis_fp_normal_sensor_test.so \
    vendor/samsung/a5y17lte/proprietary/lib64/libsynaFpSensorTestNwd.so:system/lib64/libsynaFpSensorTestNwd.so \
    vendor/samsung/a5y17lte/proprietary/bin/gpsd:system/bin/gpsd \
    vendor/samsung/a5y17lte/proprietary/etc/ca.pem:system/etc/ca.pem \
    vendor/samsung/a5y17lte/proprietary/lib64/hw/gps.default.so:system/lib64/hw/gps.default.so \
    vendor/samsung/a5y17lte/proprietary/lib/libfloatingfeature.so:system/lib/libfloatingfeature.so \
    vendor/samsung/a5y17lte/proprietary/lib64/libfloatingfeature.so:system/lib64/libfloatingfeature.so \
    vendor/samsung/a5y17lte/proprietary/lib/libwrappergps.so:system/lib/libwrappergps.so \
    vendor/samsung/a5y17lte/proprietary/lib64/libwrappergps.so:system/lib64/libwrappergps.so \
    vendor/samsung/a5y17lte/proprietary/vendor/lib/egl/libGLES_mali.so:system/vendor/lib/egl/libGLES_mali.so \
    vendor/samsung/a5y17lte/proprietary/vendor/lib64/egl/libGLES_mali.so:system/vendor/lib64/egl/libGLES_mali.so \
    vendor/samsung/a5y17lte/proprietary/vendor/firmware/fimc_is_lib.bin:system/vendor/firmware/fimc_is_lib.bin \
    vendor/samsung/a5y17lte/proprietary/vendor/firmware/mfc_fw.bin:system/vendor/firmware/mfc_fw.bin \
    vendor/samsung/a5y17lte/proprietary/app/FFFFFFFF000000000000000000000001.drbin:system/app/FFFFFFFF000000000000000000000001.drbin \
    vendor/samsung/a5y17lte/proprietary/app/mcRegistry/00060308060501020000000000000000.tlbin:system/app/mcRegistry/00060308060501020000000000000000.tlbin \
    vendor/samsung/a5y17lte/proprietary/app/mcRegistry/07010000000000000000000000000000.tlbin:system/app/mcRegistry/07010000000000000000000000000000.tlbin \
    vendor/samsung/a5y17lte/proprietary/app/mcRegistry/07060000000000000000000000000000.tlbin:system/app/mcRegistry/07060000000000000000000000000000.tlbin \
    vendor/samsung/a5y17lte/proprietary/app/mcRegistry/08130000000000000000000000000000.tlbin:system/app/mcRegistry/08130000000000000000000000000000.tlbin \
    vendor/samsung/a5y17lte/proprietary/app/mcRegistry/ffffffff000000000000000000000004.tlbin:system/app/mcRegistry/ffffffff000000000000000000000004.tlbin \
    vendor/samsung/a5y17lte/proprietary/app/mcRegistry/ffffffff000000000000000000000005.tlbin:system/app/mcRegistry/ffffffff000000000000000000000005.tlbin \
    vendor/samsung/a5y17lte/proprietary/app/mcRegistry/ffffffff00000000000000000000000a.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000a.tlbin \
    vendor/samsung/a5y17lte/proprietary/app/mcRegistry/ffffffff00000000000000000000000b.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000b.tlbin \
    vendor/samsung/a5y17lte/proprietary/app/mcRegistry/ffffffff00000000000000000000000c.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000c.tlbin \
    vendor/samsung/a5y17lte/proprietary/app/mcRegistry/ffffffff00000000000000000000000d.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000d.tlbin \
    vendor/samsung/a5y17lte/proprietary/app/mcRegistry/ffffffff00000000000000000000000f.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000f.tlbin \
    vendor/samsung/a5y17lte/proprietary/app/mcRegistry/ffffffff000000000000000000000012.tlbin:system/app/mcRegistry/ffffffff000000000000000000000012.tlbin \
    vendor/samsung/a5y17lte/proprietary/app/mcRegistry/ffffffff000000000000000000000013.tlbin:system/app/mcRegistry/ffffffff000000000000000000000013.tlbin \
    vendor/samsung/a5y17lte/proprietary/app/mcRegistry/ffffffff000000000000000000000016.tlbin:system/app/mcRegistry/ffffffff000000000000000000000016.tlbin \
    vendor/samsung/a5y17lte/proprietary/app/mcRegistry/ffffffff000000000000000000000017.tlbin:system/app/mcRegistry/ffffffff000000000000000000000017.tlbin \
    vendor/samsung/a5y17lte/proprietary/app/mcRegistry/ffffffff000000000000000000000019.tlbin:system/app/mcRegistry/ffffffff000000000000000000000019.tlbin \
    vendor/samsung/a5y17lte/proprietary/app/mcRegistry/ffffffff00000000000000000000001f.tlbin:system/app/mcRegistry/ffffffff00000000000000000000001f.tlbin \
    vendor/samsung/a5y17lte/proprietary/app/mcRegistry/ffffffff00000000000000000000002e.tlbin:system/app/mcRegistry/ffffffff00000000000000000000002e.tlbin \
    vendor/samsung/a5y17lte/proprietary/app/mcRegistry/ffffffff000000000000000000000038.tlbin:system/app/mcRegistry/ffffffff000000000000000000000038.tlbin \
    vendor/samsung/a5y17lte/proprietary/app/mcRegistry/ffffffff000000000000000000000041.tlbin:system/app/mcRegistry/ffffffff000000000000000000000041.tlbin \
    vendor/samsung/a5y17lte/proprietary/app/mcRegistry/ffffffff000000000000000000000045.tlbin:system/app/mcRegistry/ffffffff000000000000000000000045.tlbin \
    vendor/samsung/a5y17lte/proprietary/app/mcRegistry/ffffffffd00000000000000000000004.tlbin:system/app/mcRegistry/ffffffffd00000000000000000000004.tlbin \
    vendor/samsung/a5y17lte/proprietary/app/mcRegistry/ffffffffd0000000000000000000000a.tlbin:system/app/mcRegistry/ffffffffd0000000000000000000000a.tlbin \
    vendor/samsung/a5y17lte/proprietary/app/mcRegistry/ffffffffd0000000000000000000000e.tlbin:system/app/mcRegistry/ffffffffd0000000000000000000000e.tlbin \
    vendor/samsung/a5y17lte/proprietary/app/mcRegistry/ffffffffd00000000000000000000014.tlbin:system/app/mcRegistry/ffffffffd00000000000000000000014.tlbin \
    vendor/samsung/a5y17lte/proprietary/app/mcRegistry/ffffffffd00000000000000000000016.tlbin:system/app/mcRegistry/ffffffffd00000000000000000000016.tlbin \
    vendor/samsung/a5y17lte/proprietary/app/mcRegistry/ffffffffd00000000000000000000017.tlbin:system/app/mcRegistry/ffffffffd00000000000000000000017.tlbin \
    vendor/samsung/a5y17lte/proprietary/app/mcRegistry/fffffffff0000000000000000000001b.tlbin:system/app/mcRegistry/fffffffff0000000000000000000001b.tlbin \
    vendor/samsung/a5y17lte/proprietary/app/mcRegistry/fffffffff0000000000000000000001e.tlbin:system/app/mcRegistry/fffffffff0000000000000000000001e.tlbin \
    vendor/samsung/a5y17lte/proprietary/bin/mcDriverDaemon:system/bin/mcDriverDaemon \
    vendor/samsung/a5y17lte/proprietary/vendor/lib64/libMcClient.so:system/vendor/lib64/libMcClient.so \
    vendor/samsung/a5y17lte/proprietary/vendor/lib64/libMcRegistry.so:system/vendor/lib64/libMcRegistry.so \
    vendor/samsung/a5y17lte/proprietary/etc/nfc/sec_s3nrn81_rfreg.bin:system/etc/nfc/sec_s3nrn81_rfreg.bin \
    vendor/samsung/a5y17lte/proprietary/lib/hw/nfc_nci.universal7880.so:system/lib/hw/nfc_nci.universal7880.so \
    vendor/samsung/a5y17lte/proprietary/lib64/hw/nfc_nci.universal7880.so:system/lib64/hw/nfc_nci.universal7880.so \
    vendor/samsung/a5y17lte/proprietary/vendor/firmware/nfc/sec_s3nrn81_firmware.bin:system/vendor/firmware/nfc/sec_s3nrn81_firmware.bin \
    vendor/samsung/a5y17lte/proprietary/lib/omx/libOMX.Exynos.AVC.Encoder.so:system/lib/omx/libOMX.Exynos.AVC.Encoder.so \
    vendor/samsung/a5y17lte/proprietary/lib64/omx/libOMX.Exynos.AVC.Encoder.so:system/lib64/omx/libOMX.Exynos.AVC.Encoder.so \
    vendor/samsung/a5y17lte/proprietary/lib/omx/libOMX.Exynos.HEVC.Decoder.so:system/lib/omx/libOMX.Exynos.HEVC.Decoder.so \
    vendor/samsung/a5y17lte/proprietary/lib64/omx/libOMX.Exynos.HEVC.Decoder.so:system/lib64/omx/libOMX.Exynos.HEVC.Decoder.so \
    vendor/samsung/a5y17lte/proprietary/lib/omx/libOMX.Exynos.HEVC.Encoder.so:system/lib/omx/libOMX.Exynos.HEVC.Encoder.so \
    vendor/samsung/a5y17lte/proprietary/lib64/omx/libOMX.Exynos.HEVC.Encoder.so:system/lib64/omx/libOMX.Exynos.HEVC.Encoder.so \
    vendor/samsung/a5y17lte/proprietary/lib/omx/libOMX.Exynos.VP9.Decoder.so:system/lib/omx/libOMX.Exynos.VP9.Decoder.so \
    vendor/samsung/a5y17lte/proprietary/lib64/omx/libOMX.Exynos.VP9.Decoder.so:system/lib64/omx/libOMX.Exynos.VP9.Decoder.so \
    vendor/samsung/a5y17lte/proprietary/bin/rild:system/bin/rild \
    vendor/samsung/a5y17lte/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
    vendor/samsung/a5y17lte/proprietary/lib64/libreference-ril.so:system/lib64/libreference-ril.so \
    vendor/samsung/a5y17lte/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/samsung/a5y17lte/proprietary/lib64/libril.so:system/lib64/libril.so \
    vendor/samsung/a5y17lte/proprietary/lib/libsec-ril.so:system/lib/libsec-ril.so \
    vendor/samsung/a5y17lte/proprietary/lib64/libsec-ril.so:system/lib64/libsec-ril.so \
    vendor/samsung/a5y17lte/proprietary/lib/libsec-ril-dsds.so:system/lib/libsec-ril-dsds.so \
    vendor/samsung/a5y17lte/proprietary/lib64/libsec-ril-dsds.so:system/lib64/libsec-ril-dsds.so \
    vendor/samsung/a5y17lte/proprietary/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
    vendor/samsung/a5y17lte/proprietary/lib64/libsecnativefeature.so:system/lib64/libsecnativefeature.so \
    vendor/samsung/a5y17lte/proprietary/bin/sensorhubservice:system/bin/sensorhubservice \
    vendor/samsung/a5y17lte/proprietary/lib64/hw/sensors.universal7880.so:system/lib64/hw/sensors.universal7880.so \
    vendor/samsung/a5y17lte/proprietary/lib64/hw/sensorhubs.universal7880.so:system/lib64/hw/sensorhubs.universal7880.so \
    vendor/samsung/a5y17lte/proprietary/lib64/libsensorhub.so:system/lib64/libsensorhub.so \
    vendor/samsung/a5y17lte/proprietary/lib64/libsensorhubservice.so:system/lib64/libsensorhubservice.so \
    vendor/samsung/a5y17lte/proprietary/lib/libsensorlistener.so:system/lib/libsensorlistener.so \
    vendor/samsung/a5y17lte/proprietary/lib64/libsensorlistener.so:system/lib64/libsensorlistener.so \
    vendor/samsung/a5y17lte/proprietary/lib/libion.so:system/lib/libion.so \
    vendor/samsung/a5y17lte/proprietary/lib64/libion.so:system/lib64/libion.so \
    vendor/samsung/a5y17lte/proprietary/lib/hw/gralloc.exynos5.so:system/lib/hw/gralloc.exynos5.so \
    vendor/samsung/a5y17lte/proprietary/lib64/hw/gralloc.exynos5.so:system/lib64/hw/gralloc.exynos5.so \
    vendor/samsung/a5y17lte/proprietary/etc/firmware/bdwlan30.bin:system/etc/firmware/bdwlan30.bin \
    vendor/samsung/a5y17lte/proprietary/etc/firmware/bdwlan30_OLD.bin:system/etc/firmware/bdwlan30_OLD.bin \
    vendor/samsung/a5y17lte/proprietary/etc/firmware/bdwlan32.bin:system/etc/firmware/bdwlan32.bin \
    vendor/samsung/a5y17lte/proprietary/etc/firmware/otp30.bin:system/etc/firmware/otp30.bin \
    vendor/samsung/a5y17lte/proprietary/etc/firmware/qwlan30.bin:system/etc/firmware/qwlan30.bin \
    vendor/samsung/a5y17lte/proprietary/etc/firmware/qwlan30_ibss.bin:system/etc/firmware/qwlan30_ibss.bin \
    vendor/samsung/a5y17lte/proprietary/etc/firmware/Data.msc:system/etc/firmware/Data.msc \
    vendor/samsung/a5y17lte/proprietary/etc/firmware/nvm_tlv.bin:system/etc/firmware/nvm_tlv.bin \
    vendor/samsung/a5y17lte/proprietary/etc/firmware/nvm_tlv_1.3.bin:system/etc/firmware/nvm_tlv_1.3.bin \
    vendor/samsung/a5y17lte/proprietary/etc/firmware/nvm_tlv_2.1.bin:system/etc/firmware/nvm_tlv_2.1.bin \
    vendor/samsung/a5y17lte/proprietary/etc/firmware/nvm_tlv_3.0.bin:system/etc/firmware/nvm_tlv_3.0.bin \
    vendor/samsung/a5y17lte/proprietary/etc/firmware/nvm_tlv_3.2.bin:system/etc/firmware/nvm_tlv_3.2.bin \
    vendor/samsung/a5y17lte/proprietary/etc/firmware/nvm_tlv_tf_1.1.bin:system/etc/firmware/nvm_tlv_tf_1.1.bin \
    vendor/samsung/a5y17lte/proprietary/etc/firmware/rampatch_tlv.img:system/etc/firmware/rampatch_tlv.img \
    vendor/samsung/a5y17lte/proprietary/etc/firmware/rampatch_tlv_1.3.tlv:system/etc/firmware/rampatch_tlv_1.3.tlv \
    vendor/samsung/a5y17lte/proprietary/etc/firmware/rampatch_tlv_2.1.tlv:system/etc/firmware/rampatch_tlv_2.1.tlv \
    vendor/samsung/a5y17lte/proprietary/etc/firmware/rampatch_tlv_3.0.tlv:system/etc/firmware/rampatch_tlv_3.0.tlv \
    vendor/samsung/a5y17lte/proprietary/etc/firmware/rampatch_tlv_3.2.tlv:system/etc/firmware/rampatch_tlv_3.2.tlv \
    vendor/samsung/a5y17lte/proprietary/etc/firmware/rampatch_tlv_tf_1.1.tlv:system/etc/firmware/rampatch_tlv_tf_1.1.tlv \
    vendor/samsung/a5y17lte/proprietary/etc/firmware/utf30.bin:system/etc/firmware/utf30.bin \
    vendor/samsung/a5y17lte/proprietary/etc/firmware/utfbd30.bin:system/etc/firmware/utfbd30.bin \
    vendor/samsung/a5y17lte/proprietary/etc/firmware/utfbd30_OLD.bin:system/etc/firmware/utfbd30_OLD.bin \
    vendor/samsung/a5y17lte/proprietary/etc/firmware/utfbd32.bin:system/etc/firmware/utfbd32.bin \
    vendor/samsung/a5y17lte/proprietary/lib/modules/qca_cld/qca_cld_wlan.ko:system/lib/modules/qca_cld/qca_cld_wlan.ko
